### PR TITLE
Issue #85:  Fix issue where the new NotificationRestV2Controller comb…

### LINKED ISSUE #85: The new NotificationRestV2Controller combines poorly with the existing DemoNotificationService
Emergency Alerts uses a second instance of `DemoNotificationService`.  Because there are two beans of this type, each of them is reading notifications based on the `DemoNotificationService.locations` and you end up with duplicates.

### PR DESCRIPTION
**Pull request by drewwills**
…ines poorly with the existing DemoNotificationService

Fixes #85 

I'd like to get this item merged before 4.0.0.

### CODE REVIEW

File: notification-portlet-api/src/main/java/org/jasig/portlet/notice/NotificationResponse.java [hunk 1]
```diff
@@ -168,6 +169,17 @@ public NotificationResponse filterErrors(Set<Integer> hiddenErrorKeys) {
...
     }
 
+    /**
+     * Provides the total number of notifications contained in the response.
+     */
+    @JsonIgnore
+    @XmlTransient
+    public int size() {
+        final MutableInt rslt = new MutableInt(0);
+        categories.forEach(category -> rslt.add(category.getEntries().size()));
```
Comment (ChristianMurphy) [inline notification-portlet-api/src/main/java/org/jasig/portlet/notice/NotificationResponse.java]: Maybe stream sum could help? Something like:

```
Integer totalNotifications = categories
    .stream()
    .mapToInt(NotificationCategory::getEntries::size)
    .sum();
```

Comment (drewwills) [reply notification-portlet-api/src/main/java/org/jasig/portlet/notice/NotificationResponse.java]: Yeah that's perfect.  I looked for a way to add numbers together with streams... didn't find anything.
